version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "mongo"
  ]

[[code_formatters]]
name = "standardjs"

[[code_formatters]]
name = "dotnet-format"

[[code_formatters]]
name = "google-java-format"